project:
  type: website

website:
  title: "TEST DASHBOARD"
  navbar:
    left:
      - href: index.qmd
        text: Dashboard

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



